### ISSUE TITLE
Docker Releases

### ISSUE THREAD

**Issue by ohdearaugustin** [ankicommunity/anki-sync-server#149]
As the docker container build in the [anki-devops-service](https://github.com/ankicommunity/anki-devops-services) is out of date. Last release 2 years ago with version 2.1.0 to someones private dockerhub account. 

I would suggest to use the included docker registry of github, which is for free for opensource projects and doesn't have the download limitations" of dockerhub.
Furthermore the control over the registry will be within the repository.

I would also argue that the docker container should be build within the project itself.

We could also provide a develop version as container.

I can provide a PR with the implementation.

**Comment by woj-tek** [comment]
I concur that the docker build and configuration (including docker-compose.yaml) should be in the same repository as it's usually just a bunch of files.

Plus, having regular and updated builds would be awesome :-)

EDIT: already discussed here: https://github.com/ankicommunity/anki-sync-server/issues/69 but I think it got sidetracked...

**Comment by nekogitt** [comment]
Is there any development on this? I use the docker container in UnRaid and haven't had any problems until recently when my Anki application on Arch started giving me problems. So I updated to 2.1.54 and followed the directions, but I'm running into errors syncing. Now I'm thinking it's because the docker version of Anki-Sync-Server that I'm using hasn't been updated in two years and is not compatible with the latest Anki.

**Comment by ohdearaugustin** [comment]
I'm currently waiting that #148 is merged, as my PRs are kind of depend on each other.

**Comment by nekogitt** [comment]
Okay, thank you for the prompt response and all your work. Look forward to the update!
