### ISSUE TITLE
Create chat room

### ISSUE THREAD

**Issue by Sterrs** [ankicommunity/anki-sync-server#7]
It would be useful to have a chat room to be able to discuss the direction of the project. I'd recommend using [Gitter](https://gitter.im) or [Matrix](https://matrix.org) via [Riot](https://riot.im).

**Comment by VikashKothary** [comment]
I chose Gitter because I've been in used by other open source projects.

Step 1. Create Gitter community. **DONE**
- https://gitter.im/ankicommunity/community

Step 2. Add Gitter community to Open Source Documentation
- Kinda dependant on #1. Because I want to simplify up the ppen source documention, and move some of it to a wiki such as `Readthedocs` or `Github Wiki`

**Comment by Jedliu** [comment]
Is there any update for this project?

**Comment by VikashKothary** [comment]
I'll be honest, I've been busy with other things. However, please feel free to add issues and comments.
I'm happy to put some time in, if there's something specific that needs to be done

**Comment by VikashKothary** [comment]
I've added a markdown badge for the Glitter chat to the README for now. In the future, I'll add a more clear Call to Action to join the chat room. Closing the ticket for now.
